// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XebecAPI.Data;

namespace XebecAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220408105730_prepoulated")]
    partial class prepoulated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("XebecAPI.Shared.AdditionalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Disability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("AdditionalInformations");
                });

            modelBuilder.Entity("XebecAPI.Shared.AnswerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnswerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Number"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Long Text"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Short Text"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Date/Time"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Boolean"
                        },
                        new
                        {
                            Id = 6,
                            Type = "File Upload"
                        },
                        new
                        {
                            Id = 7,
                            Type = "Hybrid"
                        });
                });

            modelBuilder.Entity("XebecAPI.Shared.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ApplicationPhaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BeginApplication")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeApplied")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ApplicationPhaseId");

                    b.HasIndex("JobId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("XebecAPI.Shared.ApplicationPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationPhases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Applied"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Schedule Phone Screen"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Phone Screened"
                        },
                        new
                        {
                            Id = 25,
                            Description = "MS Teams Screened",
                            EmailTemplate = "Hi , {firstname}\r\n\r\nI received your application and would love to learn more about you and answer any questions you may have about 1Nebula or the { jobtitle } position.\r\n\r\nCould you send me a few times when you’d be available for a 30 minute Microsoft Teams call in the next few days ? I will be sending you a link to the meeting based on your availability.\r\n\r\nI look forward to our conversation,\r\n\r\n{ sentname}\r\n            { sentsurname}\r\n            { senttitle}\r\n\r\n            1Nebula"
                        },
                        new
                        {
                            Id = 26,
                            Description = "First Round Interview",
                            EmailTemplate = "Dear: {firstname} {surname},\r\n\r\nIt was so lovely chatting with you and getting to know you a bit more. \r\n\r\nI was overall impressed with your background and experience and have consulted with the team on your application for the {jobtitle} position.\r\n\r\nThe team has decided to progress you to the first stage which is the first round interview. Details of the interview are listed below. Should you be available, a Microsoft teams meeting link will be sent to your email address linked to this application.\r\n\r\nDate: {date}\r\nTime: {time}\r\nMedium: MS Teams\r\nInterview Panel: {panel}\r\n\r\nNo need to prepare anything as this will be a culture interview as the team would like to get to know you and understand your skill set in relation to your career goals.\r\n\r\nI look forward to your response.\r\nKind regards,\r\n{sentname} {sentsurname}\r\n{senttitle}\r\n1Nebula\r\nwww.1nebula.com"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Assessment Phase",
                            EmailTemplate = "Dear: {firstname} {surname},\r\n\r\nTrust you are well.\r\n\r\nIt is with great excitement we now invite you to move forward in the recruitment process with 1Nebula. The next phase will be the completion of an assessment. \r\n\r\nAttached you will find our {jobtitle}. We would like for you to present this to us via MS teams on:\r\n\r\nDate: {date}\r\nTime: {time}\r\nPresentation Panel: {panel}\r\n\r\nKindly have a look and let me know if you would like to proceed as well as confirm your availability.\r\n\r\nKind regards,\r\n{sentname} {sentsurname}\r\n{senttitle}\r\n1Nebula\r\nwww.1nebula.com"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Second Round Interview",
                            EmailTemplate = "Dear: {firstname} {surname},\r\n\r\nTrust you are well.\r\n\r\nHi {firstname},\r\n\r\nTrust you are well.\r\n\r\nWe were extremely impressed with your coding assessment and we would like for you to move forward to the next step of the Recruitment process, which is the Technical interview. It will entail getting to know you and assessing your capabilities. Details of the interview are listed below. Should you be available, a Microsoft teams meeting link will be sent to your email address linked to this application.\r\n\r\nDate: {date}\r\nTime: {time}\r\nMedium: MS Teams\r\nInterview Panel: {panel}\r\n\r\nVideo will be needed for this session so please ensure you are in a well-lit room with a strong connection and no distractions.\r\n\r\nLooking forward to your response.\r\n\r\n\r\nKind Regards,\r\n{sentname} {sentsurname}\r\n{senttitle}\r\n1Nebula\r\nwww.1nebula.com"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Waiting on Manager feedback"
                        },
                        new
                        {
                            Id = 30,
                            Description = "CTO/MD Interview"
                        },
                        new
                        {
                            Id = 31,
                            Description = "CEO Interview",
                            EmailTemplate = "Dear {firstname},\r\n\r\nWe are delighted to have you move forward to the final stage of the recruitment process. This will be your final interview with the CEO, Mr Daniel Nel.\r\n\r\n\r\nDate: {date}\r\nTime: {time}\r\nMedium: MS Teams\r\n\r\nWishing you the best of luck!\r\n\r\nRegards,\r\n{sentname} {sentsurname}\r\n(www.1nebula.com)"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Checking References",
                            EmailTemplate = "Hi {firstname},\r\n\r\nCould you please send me 3 professional references for us to contact? Be sure to include their names, titles, companies, phone numbers, and email addresses.\r\n\r\nThank you!\r\n\r\n{sentname}{sentsurname}\r\n{senttitle}\r\nOneNebula"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Offer Sent"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Offer Pending – Candidate"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Offer Pending - Second Opinion"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Final Phase"
                        });
                });

            modelBuilder.Entity("XebecAPI.Shared.ApplicationPhaseHelper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationPhaseId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeMoved")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ApplicationPhaseId");

                    b.ToTable("ApplicationPhasesHelpers");
                });

            modelBuilder.Entity("XebecAPI.Shared.CandidateRecommender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<double>("TotalMatch")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("JobId");

                    b.ToTable("CandidatesRecommender");
                });

            modelBuilder.Entity("XebecAPI.Shared.CollaboratorAssigned", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("JobId");

                    b.ToTable("CollaboratorsAssigneds");
                });

            modelBuilder.Entity("XebecAPI.Shared.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("XebecAPI.Shared.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Insitution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("XebecAPI.Shared.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Compensation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MinimumExperience")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("XebecAPI.Shared.JobAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("JobAlerts");
                });

            modelBuilder.Entity("XebecAPI.Shared.JobApplicationPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationPhaseId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationPhaseId");

                    b.HasIndex("JobId");

                    b.ToTable("JobApplicationPhases");
                });

            modelBuilder.Entity("XebecAPI.Shared.JobPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlatformName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobPlatforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlatformName = "Main 1Nebula Platform"
                        },
                        new
                        {
                            Id = 2,
                            PlatformName = "Xebec Platform"
                        },
                        new
                        {
                            Id = 3,
                            PlatformName = "48Software"
                        },
                        new
                        {
                            Id = 4,
                            PlatformName = "Oneview"
                        },
                        new
                        {
                            Id = 5,
                            PlatformName = "Stactize"
                        });
                });

            modelBuilder.Entity("XebecAPI.Shared.JobPlatformHelper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("JobPlatformId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobPlatformId");

                    b.ToTable("JobPlatformHelpers");
                });

            modelBuilder.Entity("XebecAPI.Shared.JobType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Freelance"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Contract"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Temporary"
                        },
                        new
                        {
                            Id = 6,
                            Type = "Internship"
                        });
                });

            modelBuilder.Entity("XebecAPI.Shared.JobTypeHelper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("JobTypeHelpers");
                });

            modelBuilder.Entity("XebecAPI.Shared.LoginHelper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeDateLogOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeDateLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("LoginHelpers");
                });

            modelBuilder.Entity("XebecAPI.Shared.PersonalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("PersonalInformations");
                });

            modelBuilder.Entity("XebecAPI.Shared.ProfilePortfolioLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("GitHubLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalWebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("ProfilePortfolioLinks");
                });

            modelBuilder.Entity("XebecAPI.Shared.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnswerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerTypeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("XebecAPI.Shared.QuestionnaireApplicantForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicantAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionnaireHRFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("QuestionnaireHRFormId");

                    b.ToTable("QuestionnaireApplicantForms");
                });

            modelBuilder.Entity("XebecAPI.Shared.QuestionnaireHRForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnswerTypeId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerTypeId");

                    b.HasIndex("JobId");

                    b.ToTable("QuestionnaireHRForms");
                });

            modelBuilder.Entity("XebecAPI.Shared.Reference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("RefEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("XebecAPI.Shared.RegisterHelper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeDateOfRegistration")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("RegisterHelpers");
                });

            modelBuilder.Entity("XebecAPI.Shared.RejectedCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("UnsuccessfulReasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("UnsuccessfulReasonId");

                    b.ToTable("RejectedCandidates");
                });

            modelBuilder.Entity("XebecAPI.Shared.Security.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("XebecAPI.Shared.Security.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LinkVisits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Registered")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.Security.KeyAssigner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KeysAssigned");
                });

            modelBuilder.Entity("XebecAPI.Shared.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("XebecAPI.Shared.SkillsBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillsBanks");
                });

            modelBuilder.Entity("XebecAPI.Shared.UnsuccessfulReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnsuccessfulReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Reason = "Declined Offer"
                        },
                        new
                        {
                            Id = 2,
                            Reason = "Hired Elsewhere"
                        },
                        new
                        {
                            Id = 3,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you for your interest in OneNebula!\r\n\r\n                    We received an overwhelming response to the {jobtitle} position, which makes us feel both humble and proud that so many talented individuals (like you!) want to join our team. This volume of response makes for an extremely competitive selection process. Although your background is impressive, we regret to inform you that we have decided to pursue other candidates for the position at this time.\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings. We hope you see another position that sparks your interest!\r\n\r\n                    Best wishes,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Does not fit ICP: Qualification Type"
                        },
                        new
                        {
                            Id = 4,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you for your interest in OneNebula!\r\n\r\n                    We received an overwhelming response to the {jobtitle} position, which makes us feel both humble and proud that so many talented individuals (like you!) want to join our team. This volume of response makes for an extremely competitive selection process. Although your background is impressive, we regret to inform you that we have decided to pursue other candidates for the position at this time.\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings. We hope you see another position that sparks your interest!\r\n\r\n                    Best wishes,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Does not fit ICP: University Type"
                        },
                        new
                        {
                            Id = 5,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you for your interest in OneNebula!\r\n\r\n                    We received an overwhelming response to the {jobtitle} position, which makes us feel both humble and proud that so many talented individuals (like you!) want to join our team. This volume of response makes for an extremely competitive selection process. Although your background is impressive, we regret to inform you that we have decided to pursue other candidates for the position at this time.\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings. We hope you see another position that sparks your interest!\r\n\r\n                    Best wishes,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Does not fit ICP: Salary Expectations Too High"
                        },
                        new
                        {
                            Id = 6,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you for your interest in OneNebula!\r\n\r\n                    We received an overwhelming response to the {jobtitle} position, which makes us feel both humble and proud that so many talented individuals (like you!) want to join our team. This volume of response makes for an extremely competitive selection process. Although your background is impressive, we regret to inform you that we have decided to pursue other candidates for the position at this time.\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings. We hope you see another position that sparks your interest!\r\n\r\n                    Best wishes,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Does not fit ICP: Age Category"
                        },
                        new
                        {
                            Id = 7,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you for your interest in OneNebula!\r\n\r\n                    We received an overwhelming response to the {jobtitle} position, which makes us feel both humble and proud that so many talented individuals (like you!) want to join our team. This volume of response makes for an extremely competitive selection process. Although your background is impressive, we regret to inform you that we have decided to pursue other candidates for the position at this time.\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings. We hope you see another position that sparks your interest!\r\n\r\n                    Best wishes,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Does not fit ICP: Too Junior"
                        },
                        new
                        {
                            Id = 8,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you for your interest in OneNebula!\r\n\r\n                    We received an overwhelming response to the {jobtitle} position, which makes us feel both humble and proud that so many talented individuals (like you!) want to join our team. This volume of response makes for an extremely competitive selection process. Although your background is impressive, we regret to inform you that we have decided to pursue other candidates for the position at this time.\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings. We hope you see another position that sparks your interest!\r\n\r\n                    Best wishes,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Does not fit ICP: Not in Desired Location"
                        },
                        new
                        {
                            Id = 9,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you for your interest in OneNebula!\r\n\r\n                    We received an overwhelming response to the {jobtitle} position, which makes us feel both humble and proud that so many talented individuals (like you!) want to join our team. This volume of response makes for an extremely competitive selection process. Although your background is impressive, we regret to inform you that we have decided to pursue other candidates for the position at this time.\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings. We hope you see another position that sparks your interest!\r\n\r\n                    Best wishes,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Does not fit ICP: Job Hopping"
                        },
                        new
                        {
                            Id = 10,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you for your interest in OneNebula!\r\n\r\n                    We received an overwhelming response to the {jobtitle} position, which makes us feel both humble and proud that so many talented individuals (like you!) want to join our team. This volume of response makes for an extremely competitive selection process. Although your background is impressive, we regret to inform you that we have decided to pursue other candidates for the position at this time.\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings. We hope you see another position that sparks your interest!\r\n\r\n                    Best wishes,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Does not fit ICP: References/MIE checks"
                        },
                        new
                        {
                            Id = 11,
                            Reason = "No Portfolio of Evidence"
                        },
                        new
                        {
                            Id = 12,
                            Reason = "No Response from Candidate"
                        },
                        new
                        {
                            Id = 13,
                            EmailTemplate = "Dear: {firstname},\r\n\r\n                    Trust you are well.\r\n\r\n                    We have completed the review of your coding assessment. Unfortunately upon reviewing, the team could not select you as the ideal candidate for this role as we are in need of someone a bit more senior for the current role we are recruiting for.\r\n\r\n                    However, we do see the potential in you and would love to keep your application on file for other positions that may become available in our environment.\r\n\r\n                    As one of the leaders within our industry, we receive many qualified applicants like yourself, so thank you again for taking the time to apply!\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings on our careers page. We hope you see another position that sparks your interest in the future and wish you the best in your career pursuits!\r\n\r\n                    Regards,\r\n                    {sentname}\r\n                    {senttitle}\r\n                    (www.1nebula.com)\r\n                    ",
                            Reason = "Unsuccessful Assessment"
                        },
                        new
                        {
                            Id = 14,
                            Reason = "Unsuccessful Screening: Not a culture fit"
                        },
                        new
                        {
                            Id = 15,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you again for your interest in OneNebula! I appreciated the opportunity we had to speak together, and I was overall impressed with your experience.\r\n\r\n                    Although your background is impressive, upon further review, we were unable to select you as an ideal fit for the position and current needs. As one of the leaders within our industry, we receive many qualified applicants like yourself, so thank you again for taking the time to apply!\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings on our careers page. We hope you see another position that sparks your interest in the future and wish you the best in your career pursuits!\r\n\r\n                    Regards,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Unsuccessful First Round Interview"
                        },
                        new
                        {
                            Id = 16,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you again for your interest in OneNebula! I appreciated the opportunity we had to speak together, and I was overall impressed with your experience.\r\n\r\n                    Although your background is impressive, upon further review, we were unable to select you as an ideal fit for the position and current needs. As one of the leaders within our industry, we receive many qualified applicants like yourself, so thank you again for taking the time to apply!\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings on our careers page. We hope you see another position that sparks your interest in the future and wish you the best in your career pursuits!\r\n\r\n                    Regards,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Unsuccessful Technical Interview"
                        },
                        new
                        {
                            Id = 17,
                            Reason = "No relevant experience linked to the role"
                        },
                        new
                        {
                            Id = 18,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you again for your interest in OneNebula! I appreciated the opportunity we had to speak together, and I was overall impressed with your experience.\r\n\r\n                    Although your background is impressive, upon further review, we were unable to select you as an ideal fit for the position and current needs. As one of the leaders within our industry, we receive many qualified applicants like yourself, so thank you again for taking the time to apply!\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings on our careers page. We hope you see another position that sparks your interest in the future and wish you the best in your career pursuits!\r\n\r\n                    Regards,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Unsuccessful CTO/MD interview"
                        },
                        new
                        {
                            Id = 19,
                            EmailTemplate = "Hi {firstname},\r\n\r\n                    Thank you again for your interest in OneNebula! I appreciated the opportunity we had to speak together, and I was overall impressed with your experience.\r\n\r\n                    Although your background is impressive, upon further review, we were unable to select you as an ideal fit for the position and current needs. As one of the leaders within our industry, we receive many qualified applicants like yourself, so thank you again for taking the time to apply!\r\n\r\n                    Just as we at OneNebula value our customers, we value our job candidates and invite you to review future job openings on our careers page. We hope you see another position that sparks your interest in the future and wish you the best in your career pursuits!\r\n\r\n                    Regards,\r\n                    {sentname} {sentsurname}\r\n                    {senttitle}\r\n \r\n                    OneNebula\r\n                    ",
                            Reason = "Unsuccessful CEO Interview"
                        });
                });

            modelBuilder.Entity("XebecAPI.Shared.WorkHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("WorkHistories");
                });

            modelBuilder.Entity("XebecAPI.Shared.AdditionalInformation", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.Application", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany("Applications")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XebecAPI.Shared.ApplicationPhase", "ApplicationPhase")
                        .WithMany()
                        .HasForeignKey("ApplicationPhaseId");

                    b.HasOne("XebecAPI.Shared.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationPhase");

                    b.Navigation("AppUser");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("XebecAPI.Shared.ApplicationPhaseHelper", b =>
                {
                    b.HasOne("XebecAPI.Shared.Application", "Application")
                        .WithMany("PhaseHelpers")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XebecAPI.Shared.ApplicationPhase", "ApplicationPhase")
                        .WithMany("PhaseHelpers")
                        .HasForeignKey("ApplicationPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ApplicationPhase");
                });

            modelBuilder.Entity("XebecAPI.Shared.CandidateRecommender", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XebecAPI.Shared.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("XebecAPI.Shared.CollaboratorAssigned", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XebecAPI.Shared.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("XebecAPI.Shared.Document", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.Education", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.Job", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.JobAlert", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.JobApplicationPhase", b =>
                {
                    b.HasOne("XebecAPI.Shared.ApplicationPhase", "ApplicationPhase")
                        .WithMany("JobPhases")
                        .HasForeignKey("ApplicationPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XebecAPI.Shared.Job", "Job")
                        .WithMany("JobPhases")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationPhase");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("XebecAPI.Shared.JobPlatformHelper", b =>
                {
                    b.HasOne("XebecAPI.Shared.Job", "Job")
                        .WithMany("JobPlatforms")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XebecAPI.Shared.JobPlatform", "JobPlatform")
                        .WithMany()
                        .HasForeignKey("JobPlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("JobPlatform");
                });

            modelBuilder.Entity("XebecAPI.Shared.JobTypeHelper", b =>
                {
                    b.HasOne("XebecAPI.Shared.Job", "Job")
                        .WithMany("JobTypes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XebecAPI.Shared.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("XebecAPI.Shared.LoginHelper", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.PersonalInformation", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.ProfilePortfolioLink", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.Question", b =>
                {
                    b.HasOne("XebecAPI.Shared.AnswerType", "AnswerType")
                        .WithMany()
                        .HasForeignKey("AnswerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerType");
                });

            modelBuilder.Entity("XebecAPI.Shared.QuestionnaireApplicantForm", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XebecAPI.Shared.QuestionnaireHRForm", "QuestionnaireHRForm")
                        .WithMany()
                        .HasForeignKey("QuestionnaireHRFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionnaireHRForm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XebecAPI.Shared.QuestionnaireHRForm", b =>
                {
                    b.HasOne("XebecAPI.Shared.AnswerType", "AnswerType")
                        .WithMany()
                        .HasForeignKey("AnswerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XebecAPI.Shared.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerType");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("XebecAPI.Shared.Reference", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.RegisterHelper", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.RejectedCandidate", b =>
                {
                    b.HasOne("XebecAPI.Shared.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XebecAPI.Shared.UnsuccessfulReason", "UnsuccessfulReason")
                        .WithMany("_RejectedCandidates")
                        .HasForeignKey("UnsuccessfulReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("UnsuccessfulReason");
                });

            modelBuilder.Entity("XebecAPI.Shared.Skill", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.WorkHistory", b =>
                {
                    b.HasOne("XebecAPI.Shared.Security.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("XebecAPI.Shared.Application", b =>
                {
                    b.Navigation("PhaseHelpers");
                });

            modelBuilder.Entity("XebecAPI.Shared.ApplicationPhase", b =>
                {
                    b.Navigation("JobPhases");

                    b.Navigation("PhaseHelpers");
                });

            modelBuilder.Entity("XebecAPI.Shared.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobPhases");

                    b.Navigation("JobPlatforms");

                    b.Navigation("JobTypes");
                });

            modelBuilder.Entity("XebecAPI.Shared.Security.AppUser", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("XebecAPI.Shared.UnsuccessfulReason", b =>
                {
                    b.Navigation("_RejectedCandidates");
                });
#pragma warning restore 612, 618
        }
    }
}
